// pages/_app.js
import '../styles/globals.css';
import Footer from '../components/Footer';
import Header from '../components/Header';
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Svavar Bjarnason</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="icons/favicon.ico" />
      </Head>
      <Header />
      <Component {...pageProps} />
      <Footer />
    </>
  );
}

export default MyApp;
