import Header from './Header';
import Footer from './Footer';
import Head from 'next/head';
import styles from '../styles/Layout.module.css';


export default function Layout({ children }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Svavar Bjarnason</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="icons/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>{children}</main>
      <Footer />
    </div>
  );
}
